FROM carml/go-tensorrt:ppc64le-cpu-latest
MAINTAINER Abdul Dakkak <dakkak@illinois.edu>


 # Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
ARG VCS_URL
ARG VERSION
LABEL org.tensorrt.agent.build-date=$BUILD_DATE \
      org.tensorrt.agent.name="tensorrt agent" \
      org.tensorrt.agent.description="" \
      org.tensorrt.agent.url="https://www.carml.org/" \
      org.tensorrt.agent.vcs-ref=$VCS_REF \
      org.tensorrt.agent.vcs-url=$VCS_URL \
      org.tensorrt.agent.vendor="CarML" \
      org.tensorrt.agent.version=$VERSION \
      org.tensorrt.agent.schema-version="1.0"


# Get Go bindings
ENV PKG github.com/rai-project/tensorrt
WORKDIR $GOPATH/src/$PKG

RUN git clone --depth=1 --branch=master https://${PKG}.git . && \
    glide install && \
    rm -fr vendor/github.com/Sirupsen && \
    find vendor -type f -exec sed -i 's/Sirupsen/sirupsen/g' {} + && \
    go build -a -installsuffix cgo -ldflags "-s -w -X ${PKG}/Version=${VERSION} -X ${PKG}/GitCommit=${VCS_REF} -X ${PKG}/BuildDate=${BUILD_DATE}"&& \
    cd tensorrt-agent && \
    go install && \
    cd .. && \
    rm -fr vendor

ENTRYPOINT ["tensorrt-agent", "--debug", "--verbose"]
